[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "build"

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/auth/callback"
  to = "/.netlify/functions/auth-callback"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200