[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "build"

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200